### ISSUE TITLE
Run ./p4rt-shell.sh ,but failed with  CRITICAL error

### ISSUE THREAD

**Issue by mx-zheng** [bocon13/stratum-tutorial#2]
I follow the basic guides . Now  I can run **start-mn.sh**  successfully.
![image](https://user-images.githubusercontent.com/22835075/65228460-18d98380-dafd-11e9-88de-9583666221ca.png)

But , run **p4rt-shell.sh** failed :
![image](https://user-images.githubusercontent.com/22835075/65228380-ee87c600-dafc-11e9-9636-fc8b05739912.png)

I try this on Ubuntu16.04 and CentOS 7 and  both get the same error

**Comment by mx-zheng** [comment]
![image](https://user-images.githubusercontent.com/22835075/65228751-9a311600-dafd-11e9-9568-ee9f2ec2c680.png)

**Comment by mx-zheng** [comment]
![image](https://user-images.githubusercontent.com/22835075/65229288-9fdb2b80-dafe-11e9-859f-8472a7cd7be3.png)

**Comment by ewtang** [comment]
The reason is host.docker.internal not defined under Linux.

The workaround is to replace that in the following files with ip of bridge docker0:
```
$ grep host.docker.internal *
gnmi-cli.sh:  --grpc-addr host.docker.internal:50001 $@
netcfg.json:        "managementAddress": "grpc://host.docker.internal:50001?device_id=1",
p4rt-shell.sh:# --grpc-addr host.docker.internal:50001 \
```

Bridge docker0 ip can be obtained by:
```
$ ip addr show docker0
7: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:d0:38:74:cd brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d0ff:fe38:74cd/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by bocon13** [comment]
@ewtang is right. https://github.com/docker/for-linux/issues/264 is the issue tracking this feature for Linux. In the meantime, can implement a workaround to add `host.docker.internal` to the `/etc/hosts` file. Thanks!
